### PR TITLE
Add SGX private key provider

### PR DESCRIPTION
**Pull request by qiming-007**
Add SGX private key provider and multiple threading supporting.

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by gyohuangxin** [comment]
@qiming-007 Hi, can you also raise a PR to add sgx related extension in https://github.com/intel/istio-proxy/tree/release-1.17-intel?

**Comment by qiming-007** [comment]
> @qiming-007 Hi, can you also raise a PR to add sgx related extension in https://github.com/intel/istio-proxy/tree/release-1.17-intel?

https://github.com/intel/istio-proxy/pull/18

**Review by gyohuangxin — APPROVED** [review]
LGTM, @soulxu can you review this?

**Review by soulxu — APPROVED** [review]
LGTM

**Pull request merged**
