### PR TITLE
dlb: support fallback

### PR DESCRIPTION
**Pull request by daixiang0**
Commit Message: support fallback.
Additional Description:
Risk Level:
Testing: Add

### CODE REVIEW

**Comment by gyohuangxin** [comment]
@daixiang0 Please submit the PR to release-1.19-intel branch, the main branch is not up to date. Thanks!

**Comment by gyohuangxin** [comment]
@daixiang0 Will you raise another PR for dlb fallback?

**Comment by daixiang0** [comment]
It is included in the upstream and you have merge it.

**Comment by gyohuangxin** [comment]
@daixiang0 Great! Thank you!

**Pull request closed without merging**
