### PR TITLE
Add QATzip to Release 1.17

### PR DESCRIPTION
**Pull request by giantcroc**
Signed-off-by: Changran Wang [changran.wang@intel.com](mailto:changran.wang@intel.com)

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by soulxu** [comment]
@giantcroc sorry, there is conflict, probably due to the sgx merged. would you mind rebase it? thanks!

**Comment by giantcroc** [comment]
> @giantcroc sorry, there is conflict, probably due to the sgx merged. would you mind rebase it? thanks!

OK, fixed. thanks!

**Review by soulxu — APPROVED** [review]
LGTM

**Pull request merged**
